PREFIX lwb: <http://data.lexbib.org/entity/>
PREFIX ldp: <http://data.lexbib.org/prop/direct/>
PREFIX lp: <http://data.lexbib.org/prop/>
PREFIX lps: <http://data.lexbib.org/prop/statement/>
PREFIX lpq: <http://data.lexbib.org/prop/qualifier/>

select distinct ?bibItem ?dct_title ?wikilang where
{ ?bibItem ldp:P5 lwb:Q3 .
 MINUS {?bibItem rdfs:label ?label FILTER (lang(?label)="en")}
 ?bibItem ldp:P6 ?dct_title .
 ?bibItem ldp:P11 ?publang .
 ?publang ldp:P43 ?wikilang .
}
